[DEFAULT]
SCHEMA_GOOGLE_TRENDS_TEMP=google_trends_temp 
SCHEMA_GOOGLE_TRENDS=google_trends
SCHEMA_JOB_INFO=job_info
SCHEMA_DWH_DIMENSIONS=dwh_dimensions
GOOGLE_TRENDS_DIR_DOWNLOADED_FILES=
GOOGLE_TRENDS_DIR_PARSED_FILES=
GOOGLE_TRENDS_DIR_ARCHIVED_FILES=
DIR_DOWNLOADED_FILES=
CARVAGO_DIR_DOWNLOADED_FILES=
DLT_PIPELINE_LOGS_DIR=ingestion/pipelines/logs
DLT_SOURCE_SCHEMA_DIR=ingestion/schemas/export

[GOOGLE_TRENDS]
TYPE=API
API_KEY=
RUN_CONFIGS=[{"SEARCH_PARAMETER_LIST": "vpn,antivirus,ad blocker,password manager","COUNTRY":"US","DAYS_OVERLAP":"180","TIMEZONE":"-120"}]

[WORLD_BANK]
TYPE=API
RUN_CONFIGS=[{"indicator": "NY.GDP.MKTP.CD","country":"US","output_format":"xml"},{"indicator": "SP.POP.TOTL","country":"US","output_format":"xml"}]
DIR_RAW_FILES= 
DIR_DOWNLOADED_FILES=

[FILESYSTEM]
TYPE=API
RUN_CONFIGS=[{"indicator": "ny_gdp_mktp_cd","country":"us"},{"indicator": "sp_pop_totl","country":"us"}]
DIR_RAW_FILES= 
DIR_DOWNLOADED_FILES=

[GITHUB]
TYPE=API
API_TOKEN=
RUN_CONFIGS=[{"repository": "microsoft/vscode","per_page":"100","state":"all"}]
DIR_RAW_FILES=
DIR_DOWNLOADED_FILES=

[POSTGRESQL_CONN]
TYPE=POSTGRESQL
HOST_NAME=
# HOST_NAME=host.docker.internal
PORT_NUMBER=
USERNAME=
PASSWORD=
DATABASE=
